### ISSUE TITLE
项目还在维护吗

### ISSUE THREAD

**Issue by lewis1573** [iicey/mitm#1]
我跑起来之后没有新增的xlsx，原来的xlsx文件也没有变话。现在微信的公众号已经放在订阅号里了，是接口都变了吗？

**Comment by iicey** [comment]
微信打开这个URL： https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=MzI4MzAwMDY0OA==#wechat_redirect

**Comment by lewis1573** [comment]
感谢回复，这种地址是怎么获取到的？

**Comment by iicey** [comment]
切换URL中的作者ID参数_biz
